services:
  api:
    build:
      context: .
      dockerfile: EventFlow.Api/Dockerfile
    ports:
      - "5000:8080"
    healthcheck:
      test: ["CMD", "curl","-f","http://localhost:8080/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
  worker:
    build: 
      context: .
      dockerfile: EventFlow.Worker/Dockerfile
    
  consumer-1:
    build: 
      context: .
      dockerfile: Consumer/Dockerfile
    depends_on:
      api:
        condition: service_healthy
    environment:
      EVENTFLOW_URL: http://api:8080
      EVENT_TYPE: OrderCreated
      CONSUMER_NAME: consumer-1
    ports:
      - "8081:8080"
  consumer-2:
    build:
      context: .
      dockerfile: Consumer/Dockerfile
    depends_on:
      api:
        condition: service_healthy
    environment:
      EVENTFLOW_URL: http://api:8080
      EVENT_TYPE: PaymentSuccessful
      CONSUMER_NAME: consumer-2
    ports:
      - "8082:8080"
  consumer-3:
    build:
      context: .
      dockerfile: Consumer/Dockerfile
    depends_on:
      api:
        condition: service_healthy
    environment:
      EVENTFLOW_URL: http://api:8080
      EVENT_TYPE: InventoryReserved
      CONSUMER_NAME: consumer-3
    ports:
      - "8083:8080"
  postgres:
    image: postgres:18
    container_name: eventflow-postgres
    environment:
      POSTGRES_DB: eventflow  
      POSTGRES_USER: eventflow
      POSTGRES_PASSWORD: eventflow_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
volumes:
  postgres_data:
