services:
  postgres:
    image: postgres:18
    container_name: eventflow-postgres
    environment:
      POSTGRES_DB: eventflow  
      POSTGRES_USER: eventflow
      POSTGRES_PASSWORD: eventflow_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
volumes:
  postgres_data:
